using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;
using HaloMeister.App.Localization;

namespace HaloMeister.App.Services;

/// <summary>
/// Installs a bundled IoStore overlay triplet into the game Paks folder.
/// Campaign extras (<c>MMYJ_FULL_VEHI_WAP_P</c>) carry vehicle, weapon, scenery,
/// machine, and biped palettes plus <c>hm_ally</c>/<c>hm_hostile</c> scaffolds. The fuller
/// character roster (<c>MMYJ_FULL_CHAR_P</c>) is separate. Combat behavior is
/// one pack per character. Roster and campaign edits share scenario tags, so
/// installing both writes a merged copy of each pack.
/// </summary>
public sealed class FullPalettesOverlayService
{
    public const string OverlayStem = "MMYJ_FULL_VEHI_WAP_P";
    public const string CharacterOverlayStem = "MMYJ_FULL_CHAR_P";

    private static readonly string[] Extensions = [".utoc", ".ucas", ".pak"];

    /// <summary>
    /// Trusted fingerprint of the campaign extras triplet
    /// (<c>length:SHA256</c> for .utoc|.ucas|.pak). Regenerated by
    /// <c>expand-palettes.ps1 -UpdateBundledAssets</c>.
    /// </summary>
    public const string ExpectedBundledFingerprint =
        "16736:27E6B11CAA0C226647245DD2CDC5D166979E25656F7DD6AA20523291B608BFFE|83114491:80051E3975F8D1862B320C482A7198007ACFB33FE2537AC5CCB06ECDD0315649|339:B712C03A695E34CD522446B73C4F71644A402FF141EB19CE66C269FD5676AD8C";

    /// <summary>
    /// Trusted fingerprint of the fuller character-roster triplet.
    /// </summary>
    public const string ExpectedCharacterFingerprint =
        "16736:E374A3C6BC1A31A4D0CD8D55DDE68408121708BA195C918FC03910E4F2009244|82859683:905EBF4D4AA72D20A0E53C4ABA2371C756425D124E4BE24B116BA67A43C5AA92|339:B712C03A695E34CD522446B73C4F71644A402FF141EB19CE66C269FD5676AD8C";

    /// <summary>
    /// Merged campaign file used only while the character roster is also installed.
    /// </summary>
    public const string ExpectedCombinedCampaignFingerprint =
        "16748:BA0E60930BA3011636E75CB1269DBDCEDA1E3006D33DDC191C1213244B53BDFA|83169829:4491D004D514A349D2745A84892AB5E90F3B62CA2267FA8831260CA6CFD6C0C0|339:B712C03A695E34CD522446B73C4F71644A402FF141EB19CE66C269FD5676AD8C";

    /// <summary>
    /// Merged character-roster file used only while campaign extras are also installed.
    /// </summary>
    public const string ExpectedCombinedCharacterFingerprint =
        "16748:9E4D58928FF79935464F0F2CA155A228902B079368DC96261222209C11167DA2|83169829:4491D004D514A349D2745A84892AB5E90F3B62CA2267FA8831260CA6CFD6C0C0|339:B712C03A695E34CD522446B73C4F71644A402FF141EB19CE66C269FD5676AD8C";

    public const string ExpectedTrooperFingerprint =
        "260:AC2D740263025CCA4AE2D69566FF7E66F8ADD2078759D421D1446830B3CF7E1F|49276:194AE4A1B30CCC741F88E63265A9C0793CB4AB3932E7C2DABC43657191D4C2CF|339:B712C03A695E34CD522446B73C4F71644A402FF141EB19CE66C269FD5676AD8C";
    public const string ExpectedEliteFingerprint =
        "260:B99850DE8D96F2AE69ADCA1183AC655377A9CBCBFF441D10E460513AF9C043E0|50410:567F4181B4A59EFF3BC3D60E3357D9292D7EFC79C81AA5F96DF79382E84251B5|339:B712C03A695E34CD522446B73C4F71644A402FF141EB19CE66C269FD5676AD8C";
    public const string ExpectedGruntFingerprint =
        "260:68E765A6C23D645BB07B6B448C432564C2DA79452BDC62B2D5529406E72D8207|47007:B6158C4F2F1C90B9083936C324E906060D30BE66C10E7C46DF73B577A90D1208|339:B712C03A695E34CD522446B73C4F71644A402FF141EB19CE66C269FD5676AD8C";
    public const string ExpectedJackalFingerprint =
        "260:41EB07C84B489F1961FDABB583F51FD51F9C9EBD05303F97A5AAD19FED0A7D48|45252:4AF95C0370A5591DFD6B997FFD2185F9FFC1F33E0EBDC8FD9164E524DCA2878F|339:B712C03A695E34CD522446B73C4F71644A402FF141EB19CE66C269FD5676AD8C";
    public const string ExpectedBruteFingerprint =
        "260:5DBD38C1AE1C0B1500EBB371913438335E10754F1C86D762912245F558C92929|44290:08D15A29E6CD876BA393514132C5D841383E7FDEA84DEB1AD3D0A22E5F605D79|339:B712C03A695E34CD522446B73C4F71644A402FF141EB19CE66C269FD5676AD8C";
    public const string ExpectedHunterFingerprint =
        "260:5413CF8E8625830FE29558752AF2C6B314DFF92881A1C02406728AFFE1D8FAFC|40906:FCDCDA5CA1C6CBFC4347A9FEF4941D2EC2D14E5874E75150D3DCC20F6A2C590F|339:B712C03A695E34CD522446B73C4F71644A402FF141EB19CE66C269FD5676AD8C";

    private static readonly object FingerprintCacheGate = new();
    private static string? _fingerprintCacheKey;
    private static string? _fingerprintCacheValue;

    private readonly BuiltinModDefinition _mod;

    public static IReadOnlyList<string> RequiredFileNames { get; } =
        Extensions.Select(extension => OverlayStem + extension).ToArray();

    public FullPalettesOverlayService()
        : this(BuiltinModCatalog.Campaign)
    {
    }

    public FullPalettesOverlayService(BuiltinModDefinition definition)
    {
        _mod = definition;
    }

    public BuiltinModDefinition Definition => _mod;

    public bool IsGameRunning =>
        Process.GetProcessesByName("HaloCampaignEvolved").Any(process => !process.HasExited);

    /// <summary>
    /// True only when all three overlay files are present in Paks.
    /// Dedicated features (Allegiance Demo scaffolds) should gate on the
    /// default campaign extras instance.
    /// </summary>
    public bool IsInstalled()
    {
        try
        {
            string paks = ResolvePaksDirectory();
            return HasCompleteTriplet(paks, _mod.Stem) ||
                   _mod.LegacyStems.Any(stem => HasCompleteTriplet(paks, stem));
        }
        catch (DirectoryNotFoundException)
        {
            return false;
        }
    }

    public bool IsBundledAvailable()
    {
        try
        {
            _ = ResolveBundledSources();
            return true;
        }
        catch (FileNotFoundException)
        {
            return false;
        }
    }

    /// <summary>
    /// True when the app-bundled triplet matches the trusted fingerprint for
    /// this build. Tampered or corrupt bundles must not drive update prompts.
    /// An empty expected fingerprint means the pack is not fingerprint-locked
    /// yet (used while the character AI overlay is being split out).
    /// </summary>
    public bool IsBundledIntact()
    {
        try
        {
            string[] sources = ResolveBundledSources();
            string? fingerprint = TryFingerprintFiles(sources);
            return IsTrustedFingerprint(fingerprint);
        }
        catch (FileNotFoundException)
        {
            return false;
        }
    }

    public static IReadOnlyList<BuiltinModCatalogStatus> GetCatalogStatuses()
    {
        return BuiltinModCatalog.All
            .Select(definition =>
            {
                var service = new FullPalettesOverlayService(definition);
                return new BuiltinModCatalogStatus(definition, service.GetSyncStatus());
            })
            .ToArray();
    }

    /// <summary>
    /// Compare bundled vs installed content. When the app bundle is tampered,
    /// returns <see cref="BuiltinModSyncState.BundleTampered"/> and never
    /// reports <see cref="BuiltinModSyncState.Outdated"/>.
    /// </summary>
    public BuiltinModSyncStatus GetSyncStatus()
    {
        string[]? bundledSources = null;
        try
        {
            bundledSources = ResolveBundledSources();
        }
        catch (FileNotFoundException)
        {
            return new BuiltinModSyncStatus(
                BuiltinModSyncState.BundleMissing,
                CanInstall: false,
                CanRemove: false,
                NeedsUpdatePrompt: false,
                L.Get("builtin_mod.bundle_missing"));
        }

        string? bundledFingerprint = TryFingerprintFiles(bundledSources);
        bool bundledIntact = IsTrustedFingerprint(bundledFingerprint);

        string? paks = null;
        try
        {
            paks = ResolvePaksDirectory();
        }
        catch (DirectoryNotFoundException)
        {
            if (!bundledIntact)
            {
                return new BuiltinModSyncStatus(
                    BuiltinModSyncState.BundleTampered,
                    CanInstall: false,
                    CanRemove: false,
                    NeedsUpdatePrompt: false,
                    L.Get("builtin_mod.bundle_tampered"));
            }

            return new BuiltinModSyncStatus(
                BuiltinModSyncState.GameFolderMissing,
                CanInstall: false,
                CanRemove: false,
                NeedsUpdatePrompt: false,
                L.Get("builtin_mod.game_folder_missing"));
        }

        IReadOnlyList<string> requiredNames = RequiredNames();
        int present = requiredNames.Count(name =>
            File.Exists(Path.Combine(paks, name)));
        bool shippingInstalled = HasCompleteTriplet(paks, _mod.Stem);
        bool legacyInstalled = _mod.LegacyStems.Any(stem =>
            HasCompleteTriplet(paks, stem));
        bool anyInstalledFiles = present > 0 ||
            _mod.LegacyStems.Any(stem =>
                Extensions.Any(extension =>
                    File.Exists(Path.Combine(paks, stem + extension))));

        if (!bundledIntact)
        {
            return new BuiltinModSyncStatus(
                BuiltinModSyncState.BundleTampered,
                CanInstall: false,
                CanRemove: anyInstalledFiles,
                NeedsUpdatePrompt: false,
                L.Get("builtin_mod.bundle_tampered"));
        }

        string? bundledVersion = VersionFromFingerprint(bundledFingerprint);
        if (shippingInstalled)
        {
            BuiltinModSyncStatus? pairStatus = TryScenarioPairStatus(paks, bundledVersion);
            if (pairStatus is not null)
                return pairStatus;

            string? installedFingerprint = TryFingerprintTriplet(paks, _mod.Stem);
            string? installedVersion = VersionFromFingerprint(installedFingerprint);
            if (installedFingerprint is not null &&
                bundledFingerprint is not null &&
                string.Equals(
                    installedFingerprint,
                    bundledFingerprint,
                    StringComparison.Ordinal))
            {
                return Status(
                    BuiltinModSyncState.UpToDate,
                    canInstall: false,
                    canRemove: true,
                    needsUpdatePrompt: false,
                    L.Format("builtin_mod.status_ready", bundledVersion),
                    installedVersion,
                    bundledVersion,
                    sameVersion: true);
            }

            return Status(
                BuiltinModSyncState.Outdated,
                canInstall: true,
                canRemove: true,
                needsUpdatePrompt: true,
                L.Format(
                    "builtin_mod.status_outdated",
                    installedVersion ?? L.Get("builtin_mod.version_unreadable"),
                    bundledVersion ?? L.Get("builtin_mod.version_unreadable")),
                installedVersion,
                bundledVersion,
                sameVersion: false);
        }

        if (legacyInstalled)
        {
            string? legacyVersion = VersionFromFingerprint(TryLegacyFingerprint(paks));
            return Status(
                BuiltinModSyncState.Outdated,
                canInstall: true,
                canRemove: true,
                needsUpdatePrompt: true,
                L.Format(
                    "builtin_mod.status_outdated",
                    legacyVersion ?? L.Get("builtin_mod.version_unreadable"),
                    bundledVersion ?? L.Get("builtin_mod.version_unreadable")),
                legacyVersion,
                bundledVersion,
                sameVersion: false);
        }

        if (present == 0)
        {
            return Status(
                BuiltinModSyncState.NotInstalled,
                canInstall: true,
                canRemove: anyInstalledFiles,
                needsUpdatePrompt: false,
                bundledVersion is null
                    ? L.Get("builtin_mod.status_not_installed")
                    : L.Format("builtin_mod.status_not_installed_version", bundledVersion),
                installedVersion: null,
                bundledVersion,
                sameVersion: true);
        }

        return Status(
            BuiltinModSyncState.Incomplete,
            canInstall: true,
            canRemove: true,
            needsUpdatePrompt: true,
            L.Format(
                "builtin_mod.status_incomplete",
                present,
                requiredNames.Count),
            installedVersion: null,
            bundledVersion,
            sameVersion: true);
    }

    /// <summary>
    /// Per-file presence for the shipping stem in the game Paks folder.
    /// </summary>
    public IReadOnlyList<BuiltinModFileStatus> GetInstalledFileStatus()
    {
        string? paks = null;
        try { paks = ResolvePaksDirectory(); }
        catch (DirectoryNotFoundException) { }

        return RequiredNames()
            .Select(name => new BuiltinModFileStatus(
                name,
                paks is not null && File.Exists(Path.Combine(paks, name))))
            .ToArray();
    }

    private IReadOnlyList<string> RequiredNames() =>
        Extensions.Select(extension => _mod.Stem + extension).ToArray();

    private bool IsTrustedFingerprint(string? fingerprint)
    {
        if (fingerprint is null)
            return false;
        if (string.IsNullOrEmpty(_mod.ExpectedFingerprint))
            return true;
        return string.Equals(
            fingerprint,
            _mod.ExpectedFingerprint,
            StringComparison.Ordinal);
    }

    /// <summary>
    /// Short version code for a triplet fingerprint. Same files always produce
    /// the same code; any content change produces a different one.
    /// </summary>
    public static string? VersionFromFingerprint(string? fingerprint)
    {
        if (string.IsNullOrWhiteSpace(fingerprint))
            return null;
        byte[] hash = SHA256.HashData(Encoding.UTF8.GetBytes(fingerprint));
        return Convert.ToHexString(hash.AsSpan(0, 4));
    }

    private string? TryLegacyFingerprint(string paks)
    {
        foreach (string stem in _mod.LegacyStems)
        {
            if (!HasCompleteTriplet(paks, stem))
                continue;
            return TryFingerprintTriplet(paks, stem);
        }
        return null;
    }

    private static BuiltinModSyncStatus Status(
        BuiltinModSyncState state,
        bool canInstall,
        bool canRemove,
        bool needsUpdatePrompt,
        string message,
        string? installedVersion,
        string? bundledVersion,
        bool sameVersion)
    {
        string versionText = "";
        if (!string.IsNullOrEmpty(bundledVersion))
        {
            versionText = sameVersion || string.IsNullOrEmpty(installedVersion)
                ? L.Format("builtin_mod.version_current", bundledVersion)
                : L.Format(
                    "builtin_mod.version_compare",
                    installedVersion,
                    bundledVersion);
        }

        return new BuiltinModSyncStatus(
            state,
            canInstall,
            canRemove,
            needsUpdatePrompt,
            message,
            versionText);
    }

    private static bool HasCompleteTriplet(string paks, string stem) =>
        Extensions.All(extension =>
            File.Exists(Path.Combine(paks, stem + extension)));

    private static string? TryFingerprintTriplet(string directory, string stem)
    {
        string[] paths = Extensions
            .Select(extension => Path.Combine(directory, stem + extension))
            .ToArray();
        return TryFingerprintFiles(paths);
    }

    private static string? TryFingerprintFiles(IReadOnlyList<string> paths)
    {
        try
        {
            string cacheKey = string.Join(
                '|',
                paths.Select(path =>
                {
                    var info = new FileInfo(path);
                    return $"{path}:{info.Length}:{info.LastWriteTimeUtc.Ticks}";
                }));
            lock (FingerprintCacheGate)
            {
                if (_fingerprintCacheKey == cacheKey &&
                    _fingerprintCacheValue is not null)
                {
                    return _fingerprintCacheValue;
                }
            }

            var parts = new List<string>(paths.Count);
            foreach (string path in paths)
            {
                var info = new FileInfo(path);
                using FileStream stream = File.OpenRead(path);
                byte[] hash = SHA256.HashData(stream);
                parts.Add($"{info.Length}:{Convert.ToHexString(hash)}");
            }

            string fingerprint = string.Join('|', parts);
            lock (FingerprintCacheGate)
            {
                _fingerprintCacheKey = cacheKey;
                _fingerprintCacheValue = fingerprint;
            }
            return fingerprint;
        }
        catch
        {
            return null;
        }
    }

    public FullPalettesOverlayResult Install()
    {
        EnsureGameClosed();
        string paks = ResolvePaksDirectory();
        if (_mod.Id == BuiltinModCatalog.CampaignId)
            return InstallCampaign(paks);
        if (_mod.Id == BuiltinModCatalog.CharactersId)
            return InstallCharacterRoster(paks);

        return InstallSources(ResolveBundledSources(), _mod.ExpectedFingerprint, paks, _mod.Stem);
    }

    public FullPalettesOverlayResult Remove()
    {
        EnsureGameClosed();
        string paks = ResolvePaksDirectory();
        if (_mod.Id == BuiltinModCatalog.CampaignId)
            return RemoveCampaign(paks);
        if (_mod.Id == BuiltinModCatalog.CharactersId)
            return RemoveCharacterRoster(paks);

        var removed = new List<string>();
        removed.AddRange(RemoveStem(paks, _mod.Stem));
        foreach (string stem in _mod.LegacyStems)
            removed.AddRange(RemoveStem(paks, stem));

        if (removed.Count == 0)
            throw new FileNotFoundException(
                L.Get("builtin_mod.status_not_installed"));

        return Removed(paks, removed);
    }

    private bool IsCampaignMod => _mod.Id == BuiltinModCatalog.CampaignId;

    private bool IsCharacterRosterMod => _mod.Id == BuiltinModCatalog.CharactersId;

    private BuiltinModSyncStatus? TryScenarioPairStatus(string paks, string? bundledVersion)
    {
        if (!IsCampaignMod && !IsCharacterRosterMod)
            return null;

        if (IsCombinedPairInstalled(paks))
        {
            return Status(
                BuiltinModSyncState.UpToDate,
                canInstall: false,
                canRemove: true,
                needsUpdatePrompt: false,
                L.Format("builtin_mod.status_ready", bundledVersion),
                bundledVersion,
                bundledVersion,
                sameVersion: true);
        }

        bool inconsistent;
        if (IsCampaignMod)
        {
            inconsistent = IsPaletteOnlyInstalled(paks) ||
                FingerprintEquals(paks, OverlayStem, ExpectedCombinedCampaignFingerprint);
        }
        else
        {
            inconsistent =
                FingerprintEquals(paks, CharacterOverlayStem, ExpectedCombinedCharacterFingerprint) ||
                (HasCompleteTriplet(paks, OverlayStem) &&
                 FingerprintEquals(paks, CharacterOverlayStem, ExpectedCharacterFingerprint));
        }

        if (!inconsistent)
            return null;

        string stem = IsCampaignMod ? OverlayStem : CharacterOverlayStem;
        string? installedVersion = VersionFromFingerprint(TryFingerprintTriplet(paks, stem));
        return Status(
            BuiltinModSyncState.Outdated,
            canInstall: true,
            canRemove: true,
            needsUpdatePrompt: true,
            L.Format(
                "builtin_mod.status_outdated",
                installedVersion ?? L.Get("builtin_mod.version_unreadable"),
                bundledVersion ?? L.Get("builtin_mod.version_unreadable")),
            installedVersion,
            bundledVersion,
            sameVersion: false);
    }

    private FullPalettesOverlayResult InstallCampaign(string paks)
    {
        foreach (string stem in _mod.LegacyStems)
            RemoveStem(paks, stem);
        bool merge = HasCompleteTriplet(paks, CharacterOverlayStem) &&
                     (FingerprintEquals(paks, CharacterOverlayStem, ExpectedCharacterFingerprint) ||
                      FingerprintEquals(paks, CharacterOverlayStem, ExpectedCombinedCharacterFingerprint));
        if (merge)
            return InstallCombinedPair(paks);

        return InstallSources(
            ResolveBundledSources(),
            ExpectedBundledFingerprint,
            paks,
            OverlayStem);
    }

    private FullPalettesOverlayResult InstallCharacterRoster(string paks)
    {
        if (HasCompleteTriplet(paks, OverlayStem))
            return InstallCombinedPair(paks);

        return InstallSources(
            ResolveBundledSources(),
            ExpectedCharacterFingerprint,
            paks,
            CharacterOverlayStem);
    }

    private FullPalettesOverlayResult InstallCombinedPair(string paks)
    {
        List<string> files = [];
        files.AddRange(InstallSources(
            ResolveCombinedSources(OverlayStem),
            ExpectedCombinedCampaignFingerprint,
            paks,
            OverlayStem).Files);
        files.AddRange(InstallSources(
            ResolveCombinedSources(CharacterOverlayStem),
            ExpectedCombinedCharacterFingerprint,
            paks,
            CharacterOverlayStem).Files);
        return new FullPalettesOverlayResult(
            Installed: true,
            PaksDirectory: paks,
            Files: files,
            Message: L.Get("builtin_mod.installed_restart"));
    }

    private FullPalettesOverlayResult RemoveCampaign(string paks)
    {
        bool restoreRoster = FingerprintEquals(
            paks,
            CharacterOverlayStem,
            ExpectedCombinedCharacterFingerprint);
        var removed = new List<string>();
        removed.AddRange(RemoveStem(paks, OverlayStem));
        foreach (string stem in _mod.LegacyStems)
            removed.AddRange(RemoveStem(paks, stem));
        if (removed.Count == 0)
            throw new FileNotFoundException(L.Get("builtin_mod.status_not_installed"));

        if (restoreRoster)
        {
            InstallSources(
                ResolveBundledTriplet(CharacterOverlayStem),
                ExpectedCharacterFingerprint,
                paks,
                CharacterOverlayStem);
        }

        return Removed(paks, removed);
    }

    private FullPalettesOverlayResult RemoveCharacterRoster(string paks)
    {
        bool restoreCampaign = FingerprintEquals(
            paks,
            OverlayStem,
            ExpectedCombinedCampaignFingerprint);
        List<string> removed = RemoveStem(paks, CharacterOverlayStem);
        if (removed.Count == 0)
            throw new FileNotFoundException(L.Get("builtin_mod.status_not_installed"));

        if (restoreCampaign)
        {
            InstallSources(
                ResolveBundledTriplet(OverlayStem),
                ExpectedBundledFingerprint,
                paks,
                OverlayStem);
        }

        return Removed(paks, removed);
    }

    private static FullPalettesOverlayResult Removed(string paks, IReadOnlyList<string> files) =>
        new(
            Installed: false,
            PaksDirectory: paks,
            Files: files,
            Message: L.Get("builtin_mod.removed_restart"));

    private FullPalettesOverlayResult InstallSources(
        string[] sources,
        string expectedFingerprint,
        string paks,
        string stem)
    {
        string? fingerprint = TryFingerprintFiles(sources);
        if (!string.Equals(fingerprint, expectedFingerprint, StringComparison.Ordinal))
        {
            throw new InvalidOperationException(L.Get("builtin_mod.bundle_tampered"));
        }

        RemoveStem(paks, stem);
        string[] destinations = Extensions
            .Select(extension => Path.Combine(paks, stem + extension))
            .ToArray();
        var copied = new List<string>();
        try
        {
            for (int index = 0; index < sources.Length; index++)
            {
                string temporary = destinations[index] + $".{Guid.NewGuid():N}.tmp";
                File.Copy(sources[index], temporary, false);
                File.Move(temporary, destinations[index], true);
                copied.Add(destinations[index]);
            }
        }
        catch
        {
            foreach (string file in copied)
            {
                try { File.Delete(file); }
                catch { }
            }
            throw;
        }

        return new FullPalettesOverlayResult(
            Installed: true,
            PaksDirectory: paks,
            Files: destinations,
            Message: L.Get("builtin_mod.installed_restart"));
    }

    private static bool IsCombinedPairInstalled(string paks) =>
        FingerprintEquals(paks, OverlayStem, ExpectedCombinedCampaignFingerprint) &&
        FingerprintEquals(paks, CharacterOverlayStem, ExpectedCombinedCharacterFingerprint);

    private static bool IsPaletteOnlyInstalled(string paks) =>
        FingerprintEquals(paks, CharacterOverlayStem, ExpectedCharacterFingerprint);

    private static bool FingerprintEquals(string paks, string stem, string expected) =>
        HasCompleteTriplet(paks, stem) &&
        string.Equals(
            TryFingerprintTriplet(paks, stem),
            expected,
            StringComparison.Ordinal);

    private string[] ResolveBundledTriplet(string stem) =>
        ResolveOverlayTriplet("", stem);

    private string[] ResolveCombinedSources(string stem) =>
        ResolveOverlayTriplet("Combined", stem);

    private string[] ResolveOverlayTriplet(string relativeDirectory, string stem)
    {
        foreach (string root in OverlayRoots())
        {
            string directory = string.IsNullOrEmpty(relativeDirectory)
                ? root
                : Path.Combine(root, relativeDirectory);
            string[] candidates = Extensions
                .Select(extension => Path.Combine(directory, stem + extension))
                .ToArray();
            if (candidates.All(File.Exists))
                return candidates;
        }

        throw new FileNotFoundException(L.Get("builtin_mod.bundle_missing"));
    }

    private static IEnumerable<string> OverlayRoots()
    {
        yield return Path.Combine(AppContext.BaseDirectory, "Assets", "Overlays");
        yield return Path.Combine(AppContext.BaseDirectory, "Overlays");
    }

    private void EnsureGameClosed()
    {
        if (IsGameRunning)
            throw new InvalidOperationException(
                L.Get("builtin_mod.close_game"));
    }

    private static List<string> RemoveStem(string paks, string stem)
    {
        var removed = new List<string>();
        foreach (string extension in Extensions)
        {
            string path = Path.Combine(paks, stem + extension);
            if (!File.Exists(path)) continue;
            File.Delete(path);
            removed.Add(path);
        }
        return removed;
    }

    private string[] ResolveBundledSources()
    {
        string[] roots =
        [
            Path.Combine(AppContext.BaseDirectory, "Assets", "Overlays"),
            Path.Combine(AppContext.BaseDirectory, "Overlays"),
        ];
        foreach (string root in roots)
        {
            string[] candidates = Extensions
                .Select(extension => Path.Combine(root, _mod.Stem + extension))
                .ToArray();
            if (candidates.All(File.Exists))
                return candidates;
        }

        throw new FileNotFoundException(
            L.Get("builtin_mod.bundle_missing"));
    }

    public static string ResolvePaksDirectory()
    {
        string? discovered = GameInstallationService.Current.TryGetPaksDirectory();
        if (discovered is not null)
            return discovered;

        foreach (string root in CandidateGameRoots())
        {
            string full;
            try { full = Path.GetFullPath(root); }
            catch { continue; }

            string[] candidates =
            [
                Path.Combine(full, "Content", "Meteorite", "Content", "Paks"),
                Path.Combine(full, "Meteorite", "Content", "Paks"),
                Path.Combine(full, "Content", "Paks"),
                full,
            ];
            foreach (string candidate in candidates)
                if (Directory.Exists(candidate) &&
                    Directory.EnumerateFiles(candidate, "*.utoc").Any())
                    return candidate;
        }

        throw new DirectoryNotFoundException(
            L.Get("builtin_mod.game_folder_missing"));
    }

    private static IEnumerable<string> CandidateGameRoots()
    {
        string? remembered = TryRememberedGameRoot();
        if (!string.IsNullOrWhiteSpace(remembered))
            yield return remembered!;

        foreach (string root in GameInstallationService.Current.EnumerateCandidateRoots())
            yield return root;
    }

    private static string? TryRememberedGameRoot()
    {
        try
        {
            // Binary directory is already the WinGDK/Win64 folder; walking from there
            // reaches Content\Meteorite\Content\Paks in a few hops.
            string? binaryDirectory = GameInstallationService.Current.BinaryDirectory;
            if (!string.IsNullOrWhiteSpace(binaryDirectory))
            {
                string? fromBinary = WalkToGameRoot(binaryDirectory);
                if (fromBinary is not null)
                    return fromBinary;
            }

            string? mainPath = ScriptingBridgeService.Current.FindInstalledMainPath();
            if (string.IsNullOrWhiteSpace(mainPath)) return null;
            // main.lua lives under ...\WinGDK\ue4ss\Mods\HaloMeister\Scripts\ — about
            // 8 parents up to the Store game root. Older code only walked 4 levels and
            // stopped inside WinGDK, missing Paks for Microsoft Store installs.
            return WalkToGameRoot(Path.GetDirectoryName(mainPath));
        }
        catch
        {
            return null;
        }
    }

    private static string? WalkToGameRoot(string? startDirectory)
    {
        string? directory = startDirectory;
        for (int i = 0; i < 10 && directory is not null; i++)
        {
            if (Directory.Exists(Path.Combine(directory, "Meteorite", "Content", "Paks")) ||
                Directory.Exists(Path.Combine(directory, "Content", "Meteorite", "Content", "Paks")))
            {
                return directory;
            }

            directory = Path.GetDirectoryName(directory);
        }

        return null;
    }
}

public sealed record FullPalettesOverlayResult(
    bool Installed,
    string PaksDirectory,
    IReadOnlyList<string> Files,
    string Message);

public sealed record BuiltinModFileStatus(string FileName, bool Present);

public sealed record BuiltinModCatalogStatus(
    BuiltinModDefinition Definition,
    BuiltinModSyncStatus Sync);

public enum BuiltinModSyncState
{
    BundleMissing,
    BundleTampered,
    GameFolderMissing,
    NotInstalled,
    Incomplete,
    Outdated,
    UpToDate,
}

public sealed record BuiltinModSyncStatus(
    BuiltinModSyncState State,
    bool CanInstall,
    bool CanRemove,
    bool NeedsUpdatePrompt,
    string Message,
    string VersionText = "");
